name: build-image
run-name: Build the shimboot disk image for all boards
on: [push]

jobs:
  build:
    permissions:
      contents: write

    strategy: 
      matrix:
        board: [dedede, octopus, coral, grunt, nissa, zork, corsola, jacuzzi]

    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: sudo DEBUG=1 ./build_complete.sh ${{ matrix.board }} compress_img=1 quiet=1

      - name: upload img
        uses: actions/upload-artifact@v4
        with:
          name: shimboot_${{ matrix.board }}
          path: data/shimboot_${{ matrix.board }}.bin
          compression-level: 7
  
      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: data/shimboot_${{ matrix.board }}.zip